source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
target 'Sample' do
	pod 'AsyncDisplayKit' 
    pod "SVProgressHUD"
    pod "AFNetworking"
    pod "MJExtension"
    pod 'UITableView+FDTemplateLayoutCell_Bell', '~> 1.5.0'
    pod 'SDWebImage'

end
