# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'YYKitDome--TextAttribute 1' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'YYKit'
  # Pods for YYKitDome--TextAttribute 1

end
