# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DetialText' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod ‘SDWebImage’
  # Pods for YYText
 pod "SVProgressHUD"
 pod "AFNetworking"
 pod "MJExtension"
 pod 'UITableView+FDTemplateLayoutCell_Bell', '~> 1.5.0'
end
