# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'nswy' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'UITableView+FDTemplateLayoutCell_Bell', '~> 1.5.0'
  # Pods for nswy
pod "YYKit"
end
